/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/line-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List line types */
        get: operations["list-line-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full rope record */
        get: operations["get-line"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a component (tail/lashing) to a line */
        post: operations["add-component"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List files for a line (stub until files slice) */
        get: operations["list-line-files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inspections for a line (stub until inspections slice) */
        get: operations["list-line-inspections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a line to a drum or to storage */
        post: operations["move-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List makers */
        get: operations["list-makers"];
        put?: never;
        /** Create maker */
        post: operations["create-maker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: operations["list-products"];
        put?: never;
        /** Create product */
        post: operations["create-product"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product */
        get: operations["get-product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vessels */
        get: operations["list-vessels"];
        put?: never;
        /** Create vessel */
        post: operations["create-vessel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vessel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vessel */
        get: operations["get-vessel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vessel_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deck layout (winches, drums, storage with worst-case status) */
        get: operations["get-layout"];
        /** Replace deck layout (staged edit save) */
        put: operations["save-layout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vessel_id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List mooring lines (filterable, searchable, paginated) */
        get: operations["list-lines"];
        put?: never;
        /** Register a mooring line (supports lifecycle_status=ordered) */
        post: operations["register-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Create-makerRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-makerRequest.json
             */
            readonly $schema?: string;
            name: string;
            notes?: string;
        };
        "Create-productRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-productRequest.json
             */
            readonly $schema?: string;
            can_be_turned: boolean;
            construction_type?: string;
            /** Format: double */
            default_length?: number;
            /** Format: uuid */
            line_type_id: string;
            /** Format: uuid */
            maker_id: string;
            manufacturer_manual_ref?: string;
            notes?: string;
            product_name: string;
        };
        "Create-vesselRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-vesselRequest.json
             */
            readonly $schema?: string;
            imo?: string;
            name: string;
        };
        Drum: {
            id: string;
            /** Format: int64 */
            idx: number;
            /** Format: int64 */
            line_count: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Database connectivity
             * @example ok
             */
            db: string;
            /**
             * @description Deployment scope
             * @example onboard
             */
            scope: string;
            /**
             * @description Liveness status
             * @example ok
             */
            status: string;
            /** @description Configured vessel (onboard only) */
            vessel_id?: string;
        };
        Layout: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Layout.json
             */
            readonly $schema?: string;
            storage: components["schemas"]["Storage"][] | null;
            vessel_id: string;
            winches: components["schemas"]["Winch"][] | null;
        };
        Line: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Line.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            build_age_days: number;
            can_be_turned: boolean;
            certificate_number?: string;
            certificate_ref?: string;
            components: components["schemas"]["Line"][] | null;
            construction_type?: string;
            current_condition_status?: string;
            current_drum_id?: string;
            current_side?: string;
            current_storage_id?: string;
            id: string;
            /** Format: int64 */
            install_age_days: number;
            /** Format: date-time */
            installation_date?: string;
            installed: boolean;
            /** Format: double */
            length?: number;
            lifecycle_status: string;
            line_type_name: string;
            location_label: string;
            maker_name: string;
            /** Format: date-time */
            manufacture_date?: string;
            name: string;
            /** Format: date-time */
            next_inspection_due?: string;
            parent_line_id?: string;
            product_id: string;
            product_name: string;
            serial_number: string;
            /** Format: int64 */
            side_a_age_days: number;
            /** Format: date-time */
            side_a_change_date?: string;
            side_a_condition?: string;
            /** Format: int64 */
            side_b_age_days: number;
            /** Format: date-time */
            side_b_change_date?: string;
            side_b_condition?: string;
            tag_number?: string;
            turn_due: boolean;
            vessel_id: string;
        };
        LineBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LineBody.json
             */
            readonly $schema?: string;
            certificate_number?: string;
            /** @enum {string} */
            current_side?: "A" | "B" | "n/a";
            /** Format: date */
            installation_date?: string;
            /** Format: double */
            length?: number;
            /** @enum {string} */
            lifecycle_status?: "ordered" | "active" | "spare" | "retired";
            /** Format: date */
            manufacture_date?: string;
            name: string;
            /** Format: uuid */
            product_id: string;
            serial_number: string;
            tag_number?: string;
        };
        LineRow: {
            /** Format: int64 */
            build_age_days: number;
            certificate_number?: string;
            current_condition_status?: string;
            current_side?: string;
            id: string;
            /** Format: int64 */
            install_age_days: number;
            installed: boolean;
            lifecycle_status: string;
            line_type_name: string;
            location_label: string;
            maker_name: string;
            name: string;
            /** Format: date-time */
            next_inspection_due?: string;
            product_name: string;
            serial_number: string;
            tag_number?: string;
        };
        LineType: {
            description?: string;
            id: string;
            name: string;
        };
        "List-linesResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/List-linesResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["LineRow"][] | null;
            /** Format: int64 */
            total: number;
        };
        Maker: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Maker.json
             */
            readonly $schema?: string;
            id: string;
            name: string;
            notes?: string;
        };
        "Move-lineRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Move-lineRequest.json
             */
            readonly $schema?: string;
            to_drum_id?: string;
            to_storage_id?: string;
        };
        Product: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Product.json
             */
            readonly $schema?: string;
            can_be_turned: boolean;
            construction_type?: string;
            /** Format: double */
            default_length?: number;
            id: string;
            line_type_id: string;
            line_type_name: string;
            maker_id: string;
            maker_name: string;
            manufacturer_manual_ref?: string;
            notes?: string;
            product_name: string;
        };
        "Save-layoutRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Save-layoutRequest.json
             */
            readonly $schema?: string;
            storage: components["schemas"]["StorageBody"][] | null;
            winches: components["schemas"]["WinchBody"][] | null;
        };
        Storage: {
            id: string;
            label: string;
            /** Format: int64 */
            line_count: number;
            station: string;
            worst_status?: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        StorageBody: {
            id?: string;
            label: string;
            /** @enum {string} */
            station: "fwd" | "aft";
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        Vessel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Vessel.json
             */
            readonly $schema?: string;
            id: string;
            imo?: string;
            name: string;
        };
        Winch: {
            /** Format: int64 */
            drum_count: number;
            drums: components["schemas"]["Drum"][] | null;
            id: string;
            label: string;
            /** Format: int64 */
            orientation: number;
            station: string;
            worst_status?: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        WinchBody: {
            /** Format: int64 */
            drum_count: number;
            id?: string;
            label: string;
            /**
             * Format: int64
             * @enum {integer}
             */
            orientation: 0 | 45 | -45 | 90 | -90;
            /** @enum {string} */
            station: "fwd" | "aft";
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-line-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineType"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-component": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-line-files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-line-inspections": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "move-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Move-lineRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Maker"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-maker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-makerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Maker"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-products": {
        parameters: {
            query?: {
                maker_id?: string;
                line_type_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-productRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-product": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-vessel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-vesselRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-vessel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-layout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "save-layout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Save-layoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-lines": {
        parameters: {
            query?: {
                line_type_id?: string;
                condition?: "Good" | "Monitor" | "Action";
                placement?: "installed" | "spare";
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-linesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "register-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
