/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: operations["revoke-api-key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspections/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest an inspection from the third-party API (idempotent by external_id) */
        post: operations["insp-ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspections/logbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chronological inspection logbook for a vessel */
        get: operations["insp-logbook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/line-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List line types */
        get: operations["list-line-types"];
        put?: never;
        /** Create line type */
        post: operations["create-line-type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full rope record */
        get: operations["get-line"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a certificate, manual or guide for a line */
        post: operations["file-add-cert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a component (tail/lashing) to a line */
        post: operations["add-component"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents (certificates/manuals/guides) for a line */
        get: operations["file-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inspections for a line */
        get: operations["insp-list"];
        put?: never;
        /** Log a manual inspection for a line */
        post: operations["insp-log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a line to a drum or to storage */
        post: operations["move-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List condition photos for a line */
        get: operations["file-list-photos"];
        put?: never;
        /** Upload a condition photo for a line */
        post: operations["file-add-photo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn a line to its other side */
        post: operations["turn-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List makers */
        get: operations["list-makers"];
        put?: never;
        /** Create maker */
        post: operations["create-maker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a condition photo */
        delete: operations["file-del-photo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: operations["list-products"];
        put?: never;
        /** Create product */
        post: operations["create-product"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product */
        get: operations["get-product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/condition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a condition report (CSV or PDF) */
        get: operations["insp-report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["list-users"];
        put?: never;
        /** Create user */
        post: operations["create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update user (active/role) */
        patch: operations["update-user"];
        trace?: never;
    };
    "/users/{id}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a user's API keys (metadata only) */
        get: operations["list-api-keys"];
        put?: never;
        /** Issue an API key (plaintext returned once) */
        post: operations["create-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vessels */
        get: operations["list-vessels"];
        put?: never;
        /** Create vessel */
        post: operations["create-vessel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vesselId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vessel */
        get: operations["get-vessel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vesselId}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deck layout (winches, drums, storage with worst-case status) */
        get: operations["get-layout"];
        /** Replace deck layout (staged edit save) */
        put: operations["save-layout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vesselId}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List mooring lines (filterable, searchable, paginated) */
        get: operations["list-lines"];
        put?: never;
        /** Register a mooring line (supports lifecycle_status=ordered) */
        post: operations["register-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vesselId}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vessel dashboard overview (KPIs, condition, attention, trend) */
        get: operations["over-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List fireable webhook event types */
        get: operations["list-webhook-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook subscriptions */
        get: operations["list-webhooks"];
        put?: never;
        /** Create webhook subscription */
        post: operations["create-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get webhook subscription */
        get: operations["get-webhook"];
        /** Update webhook subscription */
        put: operations["update-webhook"];
        post?: never;
        /** Delete webhook subscription */
        delete: operations["delete-webhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test delivery to a webhook */
        post: operations["test-webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIKey: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            keyPrefix: string;
            /** Format: date-time */
            lastUsedAt?: string;
            name: string;
            /** Format: date-time */
            revokedAt?: string;
            userId: string;
        };
        AuthUser: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuthUser.json
             */
            readonly $schema?: string;
            email: string;
            id: string;
            name: string;
            role: string;
            vesselId?: string;
        };
        "Create-api-keyRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-api-keyRequest.json
             */
            readonly $schema?: string;
            name: string;
        };
        "Create-line-typeRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-line-typeRequest.json
             */
            readonly $schema?: string;
            description?: string;
            name: string;
        };
        "Create-makerRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-makerRequest.json
             */
            readonly $schema?: string;
            name: string;
            notes?: string;
        };
        "Create-productRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-productRequest.json
             */
            readonly $schema?: string;
            /** Format: double */
            breakLoad?: number;
            canBeTurned: boolean;
            constructionType?: string;
            /** Format: double */
            defaultLength?: number;
            /** Format: uuid */
            lineTypeId: string;
            /** Format: uuid */
            makerId: string;
            manufacturerManualRef?: string;
            notes?: string;
            productName: string;
            /** Format: double */
            swl?: number;
        };
        "Create-userRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-userRequest.json
             */
            readonly $schema?: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "admin" | "vessel_user" | "readonly";
            /** Format: uuid */
            vesselId?: string;
        };
        "Create-vesselRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-vesselRequest.json
             */
            readonly $schema?: string;
            imo?: string;
            name: string;
        };
        Drum: {
            id: string;
            /** Format: int64 */
            idx: number;
            /** Format: int64 */
            lineCount: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        "File-add-certRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/File-add-certRequest.json
             */
            readonly $schema?: string;
            contentType?: string;
            fileBase64: string;
            fileName: string;
            /** @enum {string} */
            kind?: "certificate" | "manual" | "guide" | "delivery";
        };
        "File-add-photoRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/File-add-photoRequest.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            conditionAtCapture?: "Good" | "Monitor" | "Action";
            contentType?: string;
            fileBase64: string;
            inspectionId?: string;
            /** @enum {string} */
            side?: "A" | "B" | "n/a";
            /** Format: date */
            takenAt?: string;
        };
        FileDoc: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FileDoc.json
             */
            readonly $schema?: string;
            contentType?: string;
            /** Format: date-time */
            createdAt: string;
            fileName: string;
            fileRef: string;
            id: string;
            kind: string;
            lineId?: string;
            productId?: string;
            /** Format: int64 */
            sizeBytes: number;
            url?: string;
            vesselId?: string;
        };
        FilePhoto: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FilePhoto.json
             */
            readonly $schema?: string;
            conditionAtCapture?: string;
            /** Format: date-time */
            createdAt: string;
            fileRef: string;
            id: string;
            inspectionId?: string;
            lineId: string;
            side?: string;
            /** Format: date-time */
            takenAt?: string;
            url?: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Database connectivity
             * @example ok
             */
            db: string;
            /**
             * @description Deployment scope
             * @example onboard
             */
            scope: string;
            /**
             * @description Liveness status
             * @example ok
             */
            status: string;
            /** @description Configured vessel (onboard only) */
            vesselId?: string;
        };
        "Insp-ingestResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Insp-ingestResponse.json
             */
            readonly $schema?: string;
            created: boolean;
            inspection: components["schemas"]["Inspection"];
        };
        InspIngestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InspIngestBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            conditionStatus: "Good" | "Monitor" | "Action";
            externalId?: string;
            /** Format: date-time */
            inspectedAt?: string;
            inspectedBy?: string;
            notes?: string;
            serialNumber: string;
        };
        InspLogBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InspLogBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            conditionStatus: "Good" | "Monitor" | "Action";
            /** Format: date-time */
            inspectedAt?: string;
            inspectedBy?: string;
            notes?: string;
        };
        InspLogbookEntry: {
            conditionStatus: string;
            /** Format: date-time */
            createdAt: string;
            externalId?: string;
            id: string;
            /** Format: date-time */
            inspectedAt: string;
            inspectedBy?: string;
            lineId: string;
            lineName: string;
            notes?: string;
            serialNumber: string;
            source: string;
            vesselId: string;
        };
        Inspection: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Inspection.json
             */
            readonly $schema?: string;
            conditionStatus: string;
            /** Format: date-time */
            createdAt: string;
            externalId?: string;
            id: string;
            /** Format: date-time */
            inspectedAt: string;
            inspectedBy?: string;
            lineId: string;
            notes?: string;
            source: string;
            vesselId: string;
        };
        Layout: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Layout.json
             */
            readonly $schema?: string;
            storage: components["schemas"]["Storage"][] | null;
            vesselId: string;
            winches: components["schemas"]["Winch"][] | null;
        };
        Line: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Line.json
             */
            readonly $schema?: string;
            /** Format: double */
            breakLoad?: number;
            /** Format: int64 */
            buildAgeDays: number;
            canBeTurned: boolean;
            certificateNumber?: string;
            certificateRef?: string;
            components: components["schemas"]["Line"][] | null;
            constructionType?: string;
            currentConditionStatus?: string;
            currentDrumId?: string;
            currentSide?: string;
            currentStorageId?: string;
            id: string;
            /** Format: int64 */
            installAgeDays: number;
            /** Format: date-time */
            installationDate?: string;
            installed: boolean;
            /** Format: double */
            length?: number;
            lifecycleStatus: string;
            lineTypeName: string;
            locationLabel: string;
            makerName: string;
            /** Format: date-time */
            manufactureDate?: string;
            name: string;
            /** Format: date-time */
            nextInspectionDue?: string;
            parentLineId?: string;
            productId: string;
            productName: string;
            serialNumber: string;
            /** Format: int64 */
            sideAAgeDays: number;
            /** Format: date-time */
            sideAChangeDate?: string;
            sideACondition?: string;
            /** Format: int64 */
            sideBAgeDays: number;
            /** Format: date-time */
            sideBChangeDate?: string;
            sideBCondition?: string;
            /** Format: double */
            swl?: number;
            tagNumber?: string;
            turnDue: boolean;
            vesselId: string;
        };
        LineBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LineBody.json
             */
            readonly $schema?: string;
            certificateNumber?: string;
            /** @enum {string} */
            currentSide?: "A" | "B" | "n/a";
            /** Format: date */
            installationDate?: string;
            /** Format: double */
            length?: number;
            /** @enum {string} */
            lifecycleStatus?: "ordered" | "active" | "spare" | "retired";
            /** Format: date */
            manufactureDate?: string;
            name: string;
            /** Format: uuid */
            productId: string;
            serialNumber: string;
            tagNumber?: string;
        };
        LineRow: {
            /** Format: int64 */
            buildAgeDays: number;
            certificateNumber?: string;
            currentConditionStatus?: string;
            currentDrumId?: string;
            currentSide?: string;
            currentStorageId?: string;
            id: string;
            /** Format: int64 */
            installAgeDays: number;
            installed: boolean;
            lifecycleStatus: string;
            lineTypeName: string;
            locationLabel: string;
            makerName: string;
            name: string;
            /** Format: date-time */
            nextInspectionDue?: string;
            productName: string;
            serialNumber: string;
            tagNumber?: string;
        };
        LineType: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LineType.json
             */
            readonly $schema?: string;
            description?: string;
            id: string;
            name: string;
        };
        "List-linesResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/List-linesResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["LineRow"][] | null;
            /** Format: int64 */
            total: number;
        };
        Maker: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Maker.json
             */
            readonly $schema?: string;
            id: string;
            name: string;
            notes?: string;
        };
        "Move-lineRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Move-lineRequest.json
             */
            readonly $schema?: string;
            toDrumId?: string;
            toStorageId?: string;
        };
        NewAPIKey: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/NewAPIKey.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            keyPrefix: string;
            /** Format: date-time */
            lastUsedAt?: string;
            name: string;
            plainKey: string;
            /** Format: date-time */
            revokedAt?: string;
            userId: string;
        };
        OverAttentionItem: {
            conditionStatus: string;
            id: string;
            locationLabel: string;
            name: string;
            serialNumber: string;
        };
        OverRecentInspection: {
            conditionStatus: string;
            /** Format: date-time */
            inspectedAt: string;
            lineName: string;
        };
        OverTrendPoint: {
            /** Format: int64 */
            action: number;
            /** Format: int64 */
            inspections: number;
            month: string;
        };
        Overview: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Overview.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            action: number;
            /** Format: int64 */
            activeLines: number;
            attention: components["schemas"]["OverAttentionItem"][] | null;
            /** Format: int64 */
            avgInstallAgeDays: number;
            /** Format: int64 */
            good: number;
            /** Format: int64 */
            inspectionsDue: number;
            /** Format: int64 */
            monitor: number;
            /** Format: int64 */
            needingAttention: number;
            recentInspections: components["schemas"]["OverRecentInspection"][] | null;
            /** Format: int64 */
            spares: number;
            trend: components["schemas"]["OverTrendPoint"][] | null;
        };
        Product: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Product.json
             */
            readonly $schema?: string;
            /** Format: double */
            breakLoad?: number;
            canBeTurned: boolean;
            constructionType?: string;
            /** Format: double */
            defaultLength?: number;
            id: string;
            lineTypeId: string;
            lineTypeName: string;
            makerId: string;
            makerName: string;
            manufacturerManualRef?: string;
            notes?: string;
            productName: string;
            /** Format: double */
            swl?: number;
        };
        "Save-layoutRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Save-layoutRequest.json
             */
            readonly $schema?: string;
            storage: components["schemas"]["StorageBody"][] | null;
            winches: components["schemas"]["WinchBody"][] | null;
        };
        Storage: {
            id: string;
            label: string;
            /** Format: int64 */
            lineCount: number;
            onMap: boolean;
            station: string;
            worstStatus?: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        StorageBody: {
            id?: string;
            label: string;
            onMap?: boolean;
            station?: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        "Test-webhookResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Test-webhookResponse.json
             */
            readonly $schema?: string;
            ok: boolean;
        };
        TurnBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TurnBody.json
             */
            readonly $schema?: string;
            note?: string;
        };
        "Update-userRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Update-userRequest.json
             */
            readonly $schema?: string;
            active?: boolean;
            /** @enum {string} */
            role?: "admin" | "vessel_user" | "readonly";
        };
        User: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/User.json
             */
            readonly $schema?: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            email: string;
            id: string;
            name: string;
            role: string;
            vesselId?: string;
        };
        Vessel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Vessel.json
             */
            readonly $schema?: string;
            id: string;
            imo?: string;
            name: string;
        };
        WebhookBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/WebhookBody.json
             */
            readonly $schema?: string;
            active?: boolean;
            /** @description Event types to deliver. Empty = all events. */
            events?: string[] | null;
            /** @description Custom request headers. Values may use {{variable}} substitution. */
            headers?: {
                [key: string]: string;
            };
            name?: string;
            /** @description Body template with {{variable}} substitution. Empty = default JSON envelope. */
            payloadTemplate?: string;
            /** @description HMAC-SHA256 signing key. Leave empty on update to keep the current secret. */
            secret?: string;
            /**
             * Format: uri
             * @example https://example.com/hooks/mooring
             */
            url: string;
        };
        WebhookEventInfo: {
            description: string;
            type: string;
            variables: string[] | null;
        };
        WebhookSubscription: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/WebhookSubscription.json
             */
            readonly $schema?: string;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            events: string[] | null;
            hasSecret: boolean;
            headers: {
                [key: string]: string;
            };
            id: string;
            name: string;
            payloadTemplate?: string;
            url: string;
            vesselId?: string;
        };
        Winch: {
            /** Format: double */
            breakLoad?: number;
            driveType: string;
            /** Format: int64 */
            drumCount: number;
            drums: components["schemas"]["Drum"][] | null;
            id: string;
            label: string;
            labelAuto: boolean;
            /** Format: int64 */
            orientation: number;
            station: string;
            /** Format: double */
            swl?: number;
            worstStatus?: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        WinchBody: {
            /** Format: double */
            breakLoad?: number;
            /** @enum {string} */
            driveType?: "electric" | "hydraulic";
            /** Format: int64 */
            drumCount: number;
            id?: string;
            label: string;
            labelAuto?: boolean;
            /**
             * Format: int64
             * @enum {integer}
             */
            orientation: 0 | 45 | -45 | 90 | -90;
            /** @enum {string} */
            station: "fwd" | "aft";
            /** Format: double */
            swl?: number;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "revoke-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspIngestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insp-ingestResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-logbook": {
        parameters: {
            query?: {
                vesselId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspLogbookEntry"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-line-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineType"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-line-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-line-typeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineType"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-add-cert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["File-add-certRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDoc"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-component": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDoc"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inspection"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspLogBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inspection"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "move-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Move-lineRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-list-photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePhoto"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-add-photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["File-add-photoRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePhoto"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "turn-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Maker"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-maker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-makerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Maker"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-del-photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-products": {
        parameters: {
            query?: {
                makerId?: string;
                lineTypeId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-productRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-product": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-report": {
        parameters: {
            query?: {
                vesselId?: string;
                format?: "pdf" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-userRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Update-userRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-api-keyRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewAPIKey"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-vessel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-vesselRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-vessel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vesselId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-layout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vesselId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "save-layout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vesselId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Save-layoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-lines": {
        parameters: {
            query?: {
                lineTypeId?: string;
                condition?: "Good" | "Monitor" | "Action";
                placement?: "installed" | "spare";
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                vesselId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-linesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "register-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vesselId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "over-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vesselId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-webhook-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEventInfo"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-webhooks": {
        parameters: {
            query?: {
                vesselId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscription"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-webhook": {
        parameters: {
            query?: {
                vesselId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscription"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscription"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscription"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "test-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Test-webhookResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
