/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session */
        get: operations["auth-session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspections/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest an inspection from the third-party API (idempotent by external_id) */
        post: operations["insp-ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inspections/logbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chronological inspection logbook for a vessel */
        get: operations["insp-logbook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/line-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List line types */
        get: operations["list-line-types"];
        put?: never;
        /** Create line type */
        post: operations["create-line-type"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full rope record */
        get: operations["get-line"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/certificate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a certificate, manual or guide for a line */
        post: operations["file-add-cert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/components": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a component (tail/lashing) to a line */
        post: operations["add-component"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents (certificates/manuals/guides) for a line */
        get: operations["file-list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inspections for a line */
        get: operations["insp-list"];
        put?: never;
        /** Log a manual inspection for a line */
        post: operations["insp-log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a line to a drum or to storage */
        post: operations["move-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List condition photos for a line */
        get: operations["file-list-photos"];
        put?: never;
        /** Upload a condition photo for a line */
        post: operations["file-add-photo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lines/{id}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn a line to its other side */
        post: operations["turn-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List makers */
        get: operations["list-makers"];
        put?: never;
        /** Create maker */
        post: operations["create-maker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a condition photo */
        delete: operations["file-del-photo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: operations["list-products"];
        put?: never;
        /** Create product */
        post: operations["create-product"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product */
        get: operations["get-product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/condition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a condition report (CSV or PDF) */
        get: operations["insp-report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vessels */
        get: operations["list-vessels"];
        put?: never;
        /** Create vessel */
        post: operations["create-vessel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vessel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get vessel */
        get: operations["get-vessel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vessel_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get deck layout (winches, drums, storage with worst-case status) */
        get: operations["get-layout"];
        /** Replace deck layout (staged edit save) */
        put: operations["save-layout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vessel_id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List mooring lines (filterable, searchable, paginated) */
        get: operations["list-lines"];
        put?: never;
        /** Register a mooring line (supports lifecycle_status=ordered) */
        post: operations["register-line"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vessels/{vessel_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vessel dashboard overview (KPIs, condition, attention, trend) */
        get: operations["over-get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "Create-line-typeRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-line-typeRequest.json
             */
            readonly $schema?: string;
            description?: string;
            name: string;
        };
        "Create-makerRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-makerRequest.json
             */
            readonly $schema?: string;
            name: string;
            notes?: string;
        };
        "Create-productRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-productRequest.json
             */
            readonly $schema?: string;
            can_be_turned: boolean;
            construction_type?: string;
            /** Format: double */
            default_length?: number;
            /** Format: uuid */
            line_type_id: string;
            /** Format: uuid */
            maker_id: string;
            manufacturer_manual_ref?: string;
            notes?: string;
            product_name: string;
        };
        "Create-vesselRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Create-vesselRequest.json
             */
            readonly $schema?: string;
            imo?: string;
            name: string;
        };
        Drum: {
            id: string;
            /** Format: int64 */
            idx: number;
            /** Format: int64 */
            line_count: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        "File-add-certRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/File-add-certRequest.json
             */
            readonly $schema?: string;
            content_type?: string;
            file_base64: string;
            file_name: string;
            /** @enum {string} */
            kind?: "certificate" | "manual" | "guide";
        };
        "File-add-photoRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/File-add-photoRequest.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            condition_at_capture?: "Good" | "Monitor" | "Action";
            content_type?: string;
            file_base64: string;
            inspection_id?: string;
            /** @enum {string} */
            side?: "A" | "B" | "n/a";
            /** Format: date */
            taken_at?: string;
        };
        FileDoc: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FileDoc.json
             */
            readonly $schema?: string;
            content_type?: string;
            /** Format: date-time */
            created_at: string;
            file_name: string;
            file_ref: string;
            id: string;
            kind: string;
            line_id?: string;
            product_id?: string;
            /** Format: int64 */
            size_bytes: number;
            url?: string;
            vessel_id?: string;
        };
        FilePhoto: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FilePhoto.json
             */
            readonly $schema?: string;
            condition_at_capture?: string;
            /** Format: date-time */
            created_at: string;
            file_ref: string;
            id: string;
            inspection_id?: string;
            line_id: string;
            side?: string;
            /** Format: date-time */
            taken_at?: string;
            url?: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /**
             * @description Database connectivity
             * @example ok
             */
            db: string;
            /**
             * @description Deployment scope
             * @example onboard
             */
            scope: string;
            /**
             * @description Liveness status
             * @example ok
             */
            status: string;
            /** @description Configured vessel (onboard only) */
            vessel_id?: string;
        };
        "Insp-ingestResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Insp-ingestResponse.json
             */
            readonly $schema?: string;
            created: boolean;
            inspection: components["schemas"]["Inspection"];
        };
        InspIngestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InspIngestBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            condition_status: "Good" | "Monitor" | "Action";
            external_id?: string;
            /** Format: date-time */
            inspected_at?: string;
            inspected_by?: string;
            notes?: string;
            serial_number: string;
        };
        InspLogBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InspLogBody.json
             */
            readonly $schema?: string;
            /** @enum {string} */
            condition_status: "Good" | "Monitor" | "Action";
            /** Format: date-time */
            inspected_at?: string;
            inspected_by?: string;
            notes?: string;
        };
        InspLogbookEntry: {
            condition_status: string;
            /** Format: date-time */
            created_at: string;
            external_id?: string;
            id: string;
            /** Format: date-time */
            inspected_at: string;
            inspected_by?: string;
            line_id: string;
            line_name: string;
            notes?: string;
            serial_number: string;
            source: string;
            vessel_id: string;
        };
        Inspection: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Inspection.json
             */
            readonly $schema?: string;
            condition_status: string;
            /** Format: date-time */
            created_at: string;
            external_id?: string;
            id: string;
            /** Format: date-time */
            inspected_at: string;
            inspected_by?: string;
            line_id: string;
            notes?: string;
            source: string;
            vessel_id: string;
        };
        Layout: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Layout.json
             */
            readonly $schema?: string;
            storage: components["schemas"]["Storage"][] | null;
            vessel_id: string;
            winches: components["schemas"]["Winch"][] | null;
        };
        Line: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Line.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            build_age_days: number;
            can_be_turned: boolean;
            certificate_number?: string;
            certificate_ref?: string;
            components: components["schemas"]["Line"][] | null;
            construction_type?: string;
            current_condition_status?: string;
            current_drum_id?: string;
            current_side?: string;
            current_storage_id?: string;
            id: string;
            /** Format: int64 */
            install_age_days: number;
            /** Format: date-time */
            installation_date?: string;
            installed: boolean;
            /** Format: double */
            length?: number;
            lifecycle_status: string;
            line_type_name: string;
            location_label: string;
            maker_name: string;
            /** Format: date-time */
            manufacture_date?: string;
            name: string;
            /** Format: date-time */
            next_inspection_due?: string;
            parent_line_id?: string;
            product_id: string;
            product_name: string;
            serial_number: string;
            /** Format: int64 */
            side_a_age_days: number;
            /** Format: date-time */
            side_a_change_date?: string;
            side_a_condition?: string;
            /** Format: int64 */
            side_b_age_days: number;
            /** Format: date-time */
            side_b_change_date?: string;
            side_b_condition?: string;
            tag_number?: string;
            turn_due: boolean;
            vessel_id: string;
        };
        LineBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LineBody.json
             */
            readonly $schema?: string;
            certificate_number?: string;
            /** @enum {string} */
            current_side?: "A" | "B" | "n/a";
            /** Format: date */
            installation_date?: string;
            /** Format: double */
            length?: number;
            /** @enum {string} */
            lifecycle_status?: "ordered" | "active" | "spare" | "retired";
            /** Format: date */
            manufacture_date?: string;
            name: string;
            /** Format: uuid */
            product_id: string;
            serial_number: string;
            tag_number?: string;
        };
        LineRow: {
            /** Format: int64 */
            build_age_days: number;
            certificate_number?: string;
            current_condition_status?: string;
            current_drum_id?: string;
            current_side?: string;
            current_storage_id?: string;
            id: string;
            /** Format: int64 */
            install_age_days: number;
            installed: boolean;
            lifecycle_status: string;
            line_type_name: string;
            location_label: string;
            maker_name: string;
            name: string;
            /** Format: date-time */
            next_inspection_due?: string;
            product_name: string;
            serial_number: string;
            tag_number?: string;
        };
        LineType: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/LineType.json
             */
            readonly $schema?: string;
            description?: string;
            id: string;
            name: string;
        };
        "List-linesResponse": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/List-linesResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["LineRow"][] | null;
            /** Format: int64 */
            total: number;
        };
        Maker: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Maker.json
             */
            readonly $schema?: string;
            id: string;
            name: string;
            notes?: string;
        };
        "Move-lineRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Move-lineRequest.json
             */
            readonly $schema?: string;
            to_drum_id?: string;
            to_storage_id?: string;
        };
        OverAttentionItem: {
            condition_status: string;
            id: string;
            location_label: string;
            name: string;
            serial_number: string;
        };
        OverRecentInspection: {
            condition_status: string;
            /** Format: date-time */
            inspected_at: string;
            line_name: string;
        };
        OverTrendPoint: {
            /** Format: int64 */
            action: number;
            /** Format: int64 */
            inspections: number;
            month: string;
        };
        Overview: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Overview.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            action: number;
            /** Format: int64 */
            active_lines: number;
            attention: components["schemas"]["OverAttentionItem"][] | null;
            /** Format: int64 */
            avg_install_age_days: number;
            /** Format: int64 */
            good: number;
            /** Format: int64 */
            inspections_due: number;
            /** Format: int64 */
            monitor: number;
            /** Format: int64 */
            needing_attention: number;
            recent_inspections: components["schemas"]["OverRecentInspection"][] | null;
            /** Format: int64 */
            spares: number;
            trend: components["schemas"]["OverTrendPoint"][] | null;
        };
        Permissions: {
            admin: boolean;
            canWrite: boolean;
        };
        Product: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Product.json
             */
            readonly $schema?: string;
            can_be_turned: boolean;
            construction_type?: string;
            /** Format: double */
            default_length?: number;
            id: string;
            line_type_id: string;
            line_type_name: string;
            maker_id: string;
            maker_name: string;
            manufacturer_manual_ref?: string;
            notes?: string;
            product_name: string;
        };
        "Save-layoutRequest": {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Save-layoutRequest.json
             */
            readonly $schema?: string;
            storage: components["schemas"]["StorageBody"][] | null;
            winches: components["schemas"]["WinchBody"][] | null;
        };
        SessionOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SessionOutputBody.json
             */
            readonly $schema?: string;
            authenticated: boolean;
            groups?: string[] | null;
            permissions?: components["schemas"]["Permissions"];
            user?: components["schemas"]["SessionUser"];
        };
        SessionUser: {
            email: string;
            id: string;
            name: string;
            sub: string;
        };
        Storage: {
            id: string;
            label: string;
            /** Format: int64 */
            line_count: number;
            station: string;
            worst_status?: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        StorageBody: {
            id?: string;
            label: string;
            /** @enum {string} */
            station: "fwd" | "aft";
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        TurnBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TurnBody.json
             */
            readonly $schema?: string;
            note?: string;
        };
        Vessel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Vessel.json
             */
            readonly $schema?: string;
            id: string;
            imo?: string;
            name: string;
        };
        Winch: {
            drive_type: string;
            /** Format: int64 */
            drum_count: number;
            drums: components["schemas"]["Drum"][] | null;
            id: string;
            label: string;
            label_auto: boolean;
            /** Format: int64 */
            orientation: number;
            station: string;
            worst_status?: string;
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        WinchBody: {
            /** @enum {string} */
            drive_type?: "electric" | "hydraulic";
            /** Format: int64 */
            drum_count: number;
            id?: string;
            label: string;
            label_auto?: boolean;
            /**
             * Format: int64
             * @enum {integer}
             */
            orientation: 0 | 45 | -45 | 90 | -90;
            /** @enum {string} */
            station: "fwd" | "aft";
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspIngestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insp-ingestResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-logbook": {
        parameters: {
            query?: {
                vessel_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspLogbookEntry"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-line-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineType"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-line-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-line-typeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineType"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-add-cert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["File-add-certRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDoc"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-component": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDoc"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-list": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inspection"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspLogBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inspection"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "move-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Move-lineRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-list-photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePhoto"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-add-photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["File-add-photoRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilePhoto"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "turn-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-makers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Maker"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-maker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-makerRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Maker"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "file-del-photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-products": {
        parameters: {
            query?: {
                maker_id?: string;
                line_type_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-productRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-product": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "insp-report": {
        parameters: {
            query?: {
                vessel_id?: string;
                format?: "pdf" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    "Content-Type"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-vessel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create-vesselRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-vessel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vessel"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-layout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "save-layout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Save-layoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layout"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-lines": {
        parameters: {
            query?: {
                line_type_id?: string;
                condition?: "Good" | "Monitor" | "Action";
                placement?: "installed" | "spare";
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["List-linesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "register-line": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Line"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "over-get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
